config/routes.rb
Rails.application.routes.draw do

  resources :relays, :only => [:create, :show, :index]

  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/more/:id' => 'cart#add'
  get '/cart/less/:id' => 'cart#substract'

  resources :products
  root 'products#index'

  get 'about', to: "page#about"

  get 'faqs', to: "page#faqs"

  get 'contact', to: "page#contact"

  get 'now', to: "page#now"

  get 'css_file', to: "page#css_file"

  get 'pnb', to: "page#pnb"

  get 'page/iframe'

  resources :products

end

app/models/relay.rb
class Relay < ActiveRecord::Base
  validates :x_trans_id, presence: {message: "Must be provided!"},
                    uniqueness: true,
                    length: {minimum: 7, maximum: 10}
end

app/controllers/relays_controller.rb
class RelaysController < ApplicationController

  # Line added to avoid the verification of the authenticity_token when
  # receiving the POST request back from the payment page.
  skip_before_action :verify_authenticity_token, only: [:create]

  before_action :set_relay, only: [:show, :edit, :update, :destroy]

  # GET /relays
  # GET /relays.json
  def index
    @relays = Relay.all
  end

  # GET /relays/1
  # GET /relays/1.json
  def show
  end

  # GET /relays/new
  def new
    @relay = Relay.new
  end

  # GET /relays/1/edit
  def edit
  end

  # POST /relays
  # POST /relays.json
  def create
    @relay = Relay.new(create_params)

    respond_to do |format|
      if @relay.save
        format.html { redirect_to @relay, notice: 'A new Register in Relay was successfully created.' }
        # The following line allows to render a specific HTTP status code (comment out the previous line to make it work and modify the http_status_page in the relays views with the right HTTP code). When finished, comment out "format.html { render 'http_status_page.html.erb', status: 204 }".
        # "If you try to render content along with a non-content status code (100-199, 204, 205 or 304), it will be dropped from the response."
        # Source: http://guides.rubyonrails.org/layouts_and_rendering.html
        # format.html { render 'http_status_page.html.erb', status: 204 }
        format.json { render :show, status: :created, location: @relay }
      else
        format.html { render :new }
        format.json { render json: @relay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relays/1
  # PATCH/PUT /relays/1.json
  def update
    respond_to do |format|
      if @relay.update(relay_params)
        format.html { redirect_to @relay, notice: 'The Register in Relay was successfully updated.' }
        format.json { render :show, status: :ok, location: @relay }
      else
        format.html { render :edit }
        format.json { render json: @relay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relays/1
  # DELETE /relays/1.json
  def destroy
    @relay.destroy
    respond_to do |format|
      format.html { redirect_to relays_url, notice: 'Relay was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relay
      @relay = Relay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # The create actions has different params due to the HCO relay feature
    def relay_params
      params.require(:relay).permit(:x_type, :x_login, :x_show_form, :x_tax_exempt, :x_zip, :exact_wsp_version, :x_auth_code, :x_ship_to_last_name, :x_fax, :x_company, :exact_issname, :x_amount, :x_description, :x_avs_code, :x_ship_to_company, :x_last_name, :x_method, :x_currency_code, :x_ship_to_first_name, :x_ship_to_state, :x_ship_to_city, :x_address, :x_freight, :exact_issconf, :x_fp_sequence, :x_first_name, :x_response_subcode, :x_invoice_num, :x_fp_timestamp, :x_response_code, :x_trans_id, :x_tax, :x_email, :x_city, :x_cvv2_resp_code, :x_country, :x_ship_to_country, :x_phone, :x_ship_to_address, :x_cavv_response, :x_response_reason_code, :x_duty, :x_reference_3, :exact_ctr, :x_cust_id, :x_po_num, :x_state, :x_ship_to_zip, :x_response_reason_text, :tax2_amount, :tax1_amount, :x_recurring_billing, :x_recurring_billing_id, :x_recurring_billing_amount)
    end

    # Specific params for create action, without "require"
    # These params allow the relay response to save to the DB
    def create_params
      params.permit(:x_type, :x_login, :x_show_form, :x_tax_exempt, :x_zip, :exact_wsp_version, :x_auth_code, :x_ship_to_last_name, :x_fax, :x_company, :exact_issname, :x_amount, :x_description, :x_avs_code, :x_ship_to_company, :x_last_name, :x_method, :x_currency_code, :x_ship_to_first_name, :x_ship_to_state, :x_ship_to_city, :x_address, :x_freight, :exact_issconf, :x_fp_sequence, :x_first_name, :x_response_subcode, :x_invoice_num, :x_fp_timestamp, :x_response_code, :x_trans_id, :x_tax, :x_email, :x_city, :x_cvv2_resp_code, :x_country, :x_ship_to_country, :x_phone, :x_ship_to_address, :x_cavv_response, :x_response_reason_code, :x_duty, :x_reference_3, :exact_ctr, :x_cust_id, :x_po_num, :x_state, :x_ship_to_zip, :x_response_reason_text, :tax2_amount, :tax1_amount)
    end
end

app/helpers/relays_helper.rb
module RelaysHelper
end

app/views/relays/_form.html.erb
<%= form_for(@relay) do |f| %>
  <% if @relay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relay.errors.count, "error") %> prohibited this relay from being saved:</h2>

      <ul>
      <% @relay.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :x_show_form %><br>
    <%= f.text_field :x_show_form %>
  </div>
  <div class="field">
    <%= f.label :x_tax_exempt %><br>
    <%= f.text_field :x_tax_exempt %>
  </div>
  <div class="field">
    <%= f.label :x_zip %><br>
    <%= f.text_field :x_zip %>
  </div>
  <div class="field">
    <%= f.label :exact_wsp_version %><br>
    <%= f.text_field :exact_wsp_version %>
  </div>
  <div class="field">
    <%= f.label :x_auth_code %><br>
    <%= f.text_field :x_auth_code %>
  </div>
  <div class="field">
    <%= f.label :x_ship_to_last_name %><br>
    <%= f.text_field :x_ship_to_last_name %>
  </div>
  <div class="field">
    <%= f.label :x_fax %><br>
    <%= f.text_field :x_fax %>
  </div>
  <div class="field">
    <%= f.label :x_company %><br>
    <%= f.text_field :x_company %>
  </div>
  <div class="field">
    <%= f.label :exact_issname %><br>
    <%= f.text_field :exact_issname %>
  </div>
  <div class="field">
    <%= f.label :x_login %><br>
    <%= f.text_field :x_login %>
  </div>
  <div class="field">
    <%= f.label :x_amount %><br>
    <%= f.text_field :x_amount %>
  </div>
  <div class="field">
    <%= f.label :x_description %><br>
    <%= f.text_field :x_description %>
  </div>
  <div class="field">
    <%= f.label :x_avs_code %><br>
    <%= f.text_field :x_avs_code %>
  </div>
  <div class="field">
    <%= f.label :x_ship_to_company %><br>
    <%= f.text_field :x_ship_to_company %>
  </div>
  <div class="field">
    <%= f.label :x_last_name %><br>
    <%= f.text_field :x_last_name %>
  </div>
  <div class="field">
    <%= f.label :x_method %><br>
    <%= f.text_field :x_method %>
  </div>
  <div class="field">
    <%= f.label :x_currency_code %><br>
    <%= f.text_field :x_currency_code %>
  </div>
  <div class="field">
    <%= f.label :x_ship_to_first_name %><br>
    <%= f.text_field :x_ship_to_first_name %>
  </div>
  <div class="field">
    <%= f.label :x_ship_to_state %><br>
    <%= f.text_field :x_ship_to_state %>
  </div>
  <div class="field">
    <%= f.label :x_ship_to_city %><br>
    <%= f.text_field :x_ship_to_city %>
  </div>
  <div class="field">
    <%= f.label :x_address %><br>
    <%= f.text_field :x_address %>
  </div>
  <div class="field">
    <%= f.label :x_freight %><br>
    <%= f.text_field :x_freight %>
  </div>
  <div class="field">
    <%= f.label :exact_issconf %><br>
    <%= f.text_field :exact_issconf %>
  </div>
  <div class="field">
    <%= f.label :x_fp_sequence %><br>
    <%= f.text_field :x_fp_sequence %>
  </div>
  <div class="field">
    <%= f.label :x_first_name %><br>
    <%= f.text_field :x_first_name %>
  </div>
  <div class="field">
    <%= f.label :x_response_subcode %><br>
    <%= f.text_field :x_response_subcode %>
  </div>
  <div class="field">
    <%= f.label :x_invoice_num %><br>
    <%= f.text_field :x_invoice_num %>
  </div>
  <div class="field">
    <%= f.label :x_fp_timestamp %><br>
    <%= f.text_field :x_fp_timestamp %>
  </div>
  <div class="field">
    <%= f.label :x_response_code %><br>
    <%= f.text_field :x_response_code %>
  </div>
  <div class="field">
    <%= f.label :x_trans_id %><br>
    <%= f.text_field :x_trans_id %>
  </div>
  <div class="field">
    <%= f.label :x_tax %><br>
    <%= f.text_field :x_tax %>
  </div>
  <div class="field">
    <%= f.label :x_email %><br>
    <%= f.text_field :x_email %>
  </div>
  <div class="field">
    <%= f.label :x_city %><br>
    <%= f.text_field :x_city %>
  </div>
  <div class="field">
    <%= f.label :x_cvv2_resp_code %><br>
    <%= f.text_field :x_cvv2_resp_code %>
  </div>
  <div class="field">
    <%= f.label :x_country %><br>
    <%= f.text_field :x_country %>
  </div>
  <div class="field">
    <%= f.label :x_ship_to_country %><br>
    <%= f.text_field :x_ship_to_country %>
  </div>
  <div class="field">
    <%= f.label :x_phone %><br>
    <%= f.text_field :x_phone %>
  </div>
  <div class="field">
    <%= f.label :x_ship_to_address %><br>
    <%= f.text_field :x_ship_to_address %>
  </div>
  <div class="field">
    <%= f.label :x_cavv_response %><br>
    <%= f.text_field :x_cavv_response %>
  </div>
  <div class="field">
    <%= f.label :x_response_reason_code %><br>
    <%= f.text_field :x_response_reason_code %>
  </div>
  <div class="field">
    <%= f.label :x_duty %><br>
    <%= f.text_field :x_duty %>
  </div>
  <div class="field">
    <%= f.label :x_reference_3 %><br>
    <%= f.text_field :x_reference_3 %>
  </div>
  <div class="field">
    <%= f.label :exact_ctr %><br>
    <%= f.text_area :exact_ctr %>
  </div>
  <div class="field">
    <%= f.label :x_cust_id %><br>
    <%= f.text_field :x_cust_id %>
  </div>
  <div class="field">
    <%= f.label :x_type %><br>
    <%= f.text_field :x_type %>
  </div>
  <div class="field">
    <%= f.label :x_po_num %><br>
    <%= f.text_field :x_po_num %>
  </div>
  <div class="field">
    <%= f.label :x_state %><br>
    <%= f.text_field :x_state %>
  </div>
  <div class="field">
    <%= f.label :x_ship_to_zip %><br>
    <%= f.text_field :x_ship_to_zip %>
  </div>
  <div class="field">
    <%= f.label :x_response_reason_text %><br>
    <%= f.text_field :x_response_reason_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relays/edit.html.erb
<h1>Editing Relay</h1>

<%= render 'form' %>

<%= link_to 'Show', @relay %> |
<%= link_to 'Back', relays_path %>

app/views/relays/http_status_page.html.erb
<h1>HTTP status code: 204</h1>

app/views/relays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Transactions</h1>
<br>

<h1 class="apart"><%= link_to "Continue Shopping", products_path %></h1>

<table>
  <col width="150">
  <col width="450">
  <col width="150">
  <col width="150">
  <col width="200">
  <col width="200">
  <col width="200">
  <thead>
    <tr>
      <th>Transaction Tag</th>
      <th>Receipt</th>
      <th>Invoice No.</th>
      <th>P.O. No.</th>
      <th>Name</th>
      <th>Email</th>
      <!-- th colspan="3">Action</th -->
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <%# Used reverse_each to show the newest items at the top of the table %>
    <% @relays.reverse_each do |relay| %>
      <tr>
        <td><%= relay.x_trans_id %></td>
        <td><%= simple_format(relay.exact_ctr) %></td>
        <td><%= relay.x_invoice_num %></td>
        <td><%= relay.x_po_num %></td>
        <td><%= relay.x_first_name + " " + relay.x_last_name %></td>
        <td><%= relay.x_email %></td>
        <td><%= link_to 'Show More Details', relay %></td>
        <%# Edit is not allowed %>
        <!-- td><%#= link_to 'Edit', edit_relay_path(relay) %></td -->
        <%# Destroy is not allowed %>
        <!-- td><%#= link_to 'Destroy', relay, method: :delete, data: { confirm: 'Are you sure?' } %></td -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# New is not allowed %>
<%#= link_to 'New Relay', new_relay_path %>

app/views/relays/new.html.erb
<h1>New Relay</h1>

<%= render 'form' %>

<%= link_to 'Back', relays_path %>

app/views/relays/show.html.erb
<!-- p id="notice"><%= notice %></p -->
<br>
<h2>Data saved to the DB from the Silent Post</h2>
<br>

<h1 class="apart"><%= link_to "Continue Shopping", products_path %></h1>
<br><br>

<table>
  <col width="220">
  <col width="150">
  <thead>
    <tr>
      <th>Data Base Fields</th>
      <th>Values</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td class="bold">exact_ctr</td>
        <td class="right_aligned"><%= simple_format(@relay.exact_ctr) %></td>
      </tr>
      <tr>
        <td class="bold">x_trans_id</td>
        <td class="right_aligned"><%= @relay.x_trans_id %></td>
      </tr>
      <tr>
        <td class="bold">x_login</td>
        <td class="right_aligned"><%= @relay.x_login %></td>
      </tr>
      <tr>
        <td class="bold">x_response_reason_text</td>
        <td class="right_aligned"><%= @relay.x_response_reason_text %></td>
      </tr>
      <tr>
        <td class="bold">x_type</td>
        <td class="right_aligned"><%= @relay.x_type %></td>
      </tr>
      <tr>
        <td class="bold">x_auth_code</td>
        <td class="right_aligned"><%= @relay.x_auth_code %></td>
      </tr>
      <tr>
        <td class="bold">x_show_form</td>
        <td class="right_aligned"><%= @relay.x_show_form %></td>
      </tr>
      <tr>
        <td class="bold">x_response_code</td>
        <td class="right_aligned"><%= @relay.x_response_code %></td>
      </tr>
      <tr>
        <td class="bold">x_response_subcode</td>
        <td class="right_aligned"><%= @relay.x_response_subcode %></td>
      </tr>
      <tr>
        <td class="bold">x_avs_code</td>
        <td class="right_aligned"><%= @relay.x_avs_code %></td>
      </tr>
      <tr>
        <td class="bold">x_cvv2_resp_code</td>
        <td class="right_aligned"><%= @relay.x_cvv2_resp_code %></td>
      </tr>
      <tr>
        <td class="bold">x_cavv_response</td>
        <td class="right_aligned"><%= @relay.x_cavv_response %></td>
      </tr>
      <tr>
        <td class="bold">x_response_reason_code</td>
        <td class="right_aligned"><%= @relay.x_response_reason_code %></td>
      </tr>
      <tr>
        <td class="bold">x_fp_timestamp</td>
        <td class="right_aligned"><%= @relay.x_fp_timestamp %></td>
      </tr>
      <tr>
        <td class="bold">x_fp_sequence</td>
        <td class="right_aligned"><%= @relay.x_fp_sequence %></td>
      </tr>
      <tr>
        <td class="bold">x_amount</td>
        <td class="right_aligned"><%= @relay.x_amount %></td>
      </tr>
      <tr>
        <td class="bold">x_currency_code</td>
        <td class="right_aligned"><%= @relay.x_currency_code %></td>
      </tr>
      <tr>
        <td class="bold">x_freight</td>
        <td class="right_aligned"><%= @relay.x_freight %></td>
      </tr>
      <tr>
        <td class="bold">x_tax_exempt</td>
        <td class="right_aligned"><%= @relay.x_tax_exempt %></td>
      </tr>
      <tr>
        <td class="bold">tax2_amount</td>
        <td class="right_aligned"><%= @relay.tax2_amount %></td>
      </tr>
      <tr>
        <td class="bold">tax1_amount</td>
        <td class="right_aligned"><%= @relay.tax1_amount %></td>
      </tr>
      <tr>
        <td class="bold">x_tax</td>
        <td class="right_aligned"><%= @relay.x_tax %></td>
      </tr>
      <tr>
        <td class="bold">x_duty</td>
        <td class="right_aligned"><%= @relay.x_duty %></td>
      </tr>
      <tr>
        <td class="bold">x_description</td>
        <td class="right_aligned"><%= @relay.x_description %></td>
      </tr>

      <tr>
        <td class="bold">x_cust_id</td>
        <td class="right_aligned"><%= @relay.x_cust_id %></td>
      </tr>
      <tr>
        <td class="bold">exact_issname</td>
        <td class="right_aligned"><%= @relay.exact_issname %></td>
      </tr>
      <tr>
        <td class="bold">exact_wsp_version</td>
        <td class="right_aligned"><%= @relay.exact_wsp_version %></td>
      </tr>
      <tr>
        <td class="bold">x_method</td>
        <td class="right_aligned"><%= @relay.x_method %></td>
      </tr>
      <tr>
        <td class="bold">x_reference_3</td>
        <td class="right_aligned"><%= @relay.x_reference_3 %></td>
      </tr>
      <tr>
        <td class="bold">x_invoice_num</td>
        <td class="right_aligned"><%= @relay.x_invoice_num %></td>
      </tr>
      <tr>
        <td class="bold">x_po_num</td>
        <td class="right_aligned"><%= @relay.x_po_num %></td>
      </tr>
      <tr>
        <td class="bold">x_first_name</td>
        <td class="right_aligned"><%= @relay.x_first_name %></td>
      </tr>
      <tr>
        <td class="bold">x_last_name</td>
        <td class="right_aligned"><%= @relay.x_last_name %></td>
      </tr>
      <tr>
        <td class="bold">x_company</td>
        <td class="right_aligned"><%= @relay.x_company %></td>
      </tr>
      <tr>
        <td class="bold">x_address</td>
        <td class="right_aligned"><%= @relay.x_address %></td>
      </tr>
      <tr>
        <td class="bold">x_city</td>
        <td class="right_aligned"><%= @relay.x_city %></td>
      </tr>
      <tr>
        <td class="bold">x_state</td>
        <td class="right_aligned"><%= @relay.x_state %></td>
      </tr>
      <tr>
        <td class="bold">x_zip</td>
        <td class="right_aligned"><%= @relay.x_zip %></td>
      </tr>
      <tr>
        <td class="bold">x_country</td>
        <td class="right_aligned"><%= @relay.x_country %></td>
      </tr>
      <tr>
        <td class="bold">x_fax</td>
        <td class="right_aligned"><%= @relay.x_fax %></td>
      </tr>
      <tr>
        <td class="bold">x_email</td>
        <td class="right_aligned"><%= @relay.x_email %></td>
      </tr>
      <tr>
        <td class="bold">x_phone</td>
        <td class="right_aligned"><%= @relay.x_phone %></td>
      </tr>


      <tr>
        <td class="bold">x_ship_to_first_name</td>
        <td class="right_aligned"><%= @relay.x_ship_to_first_name %></td>
      </tr>
      <tr>
        <td class="bold">x_ship_to_last_name</td>
        <td class="right_aligned"><%= @relay.x_ship_to_last_name %></td>
      </tr>
      <tr>
        <td class="bold">x_ship_to_company</td>
        <td class="right_aligned"><%= @relay.x_ship_to_company %></td>
      </tr>
      <tr>
        <td class="bold">x_ship_to_address</td>
        <td class="right_aligned"><%= @relay.x_ship_to_address %></td>
      </tr>
      <tr>
        <td class="bold">x_ship_to_city</td>
        <td class="right_aligned"><%= @relay.x_ship_to_city %></td>
      </tr>
      <tr>
        <td class="bold">x_ship_to_state</td>
        <td class="right_aligned"><%= @relay.x_ship_to_state %></td>
      </tr>
      <tr>
        <td class="bold">x_ship_to_zip</td>
        <td class="right_aligned"><%= @relay.x_ship_to_zip %></td>
      </tr>
      <tr>
        <td class="bold">x_ship_to_country</td>
        <td class="right_aligned"><%= @relay.x_ship_to_country %></td>
      </tr>
  </tbody>
</table>
<br><br>

<%# Edit is not allowed %>
<%#= link_to 'Edit', edit_relay_path(@relay) %> <%#=|%>
<%#= link_to 'Back', relays_path %>