config/routes.rb
Rails.application.routes.draw do

  resources :relays, :only => [:create, :show, :index]

  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/more/:id' => 'cart#add'
  get '/cart/less/:id' => 'cart#substract'

  resources :products
  root 'products#index'

  get 'about', to: "page#about"

  get 'faqs', to: "page#faqs"

  get 'contact', to: "page#contact"

  get 'now', to: "page#now"

  get 'css_file', to: "page#css_file"

  get 'pnb', to: "page#pnb"

  get 'page/iframe'

  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :category, :subcategory, :x_first_name)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<% if current_user.admin? %>

  <%= form_for(@product) do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :image_url %><br>
      <%= f.text_field :image_url %>
    </div>
    <div class="field">
      <%= f.label :price %><br>
      <%= f.number_field :price, step: :any %> <%= current_user.currency_code %>
      <p>To modify the display currency of your product, please modify the Currency Code in <a href="/users/edit">your profile.</a></p>
    </div>
    <div class="field">
      <%= f.label :category %><br>
      <%= f.text_field :category %>
    </div>
    <div class="field">
      <%= f.label :subcategory %><br>
      <%= f.text_field :subcategory %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else  %>

  <br><br>
  <h2>You have to be an Administrator to be able to create/modify a product. </h2>

<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Products</h1>
<br><br>
<% if current_user.try(:admin?) %>
  <h2 class="apart"><%= link_to 'Add a new Product', new_product_path %></h2>
<% end %>

<% @products.each do |product| %>
  <div class="tile">
    <div><%= image_tag product.image_url, class: "image_size" %></div>
    <h2 class="text_bckg"><%= product.title %></h2>
    <br>
    <p class="text_bckg"><%= product.description %></p>
    <br>
    <% if current_user == nil  %>
      <% currency_code = "USD" %>
      <h3 class="text_bckg"><b class="text_bckg">Unit Price: <%= number_to_currency(product.price, unit: "#{currency_code}", format: "%n %u") %></b></h3>
    <% else  %>
      <h3 class="text_bckg"><b class="text_bckg">Unit Price: <%= number_to_currency(product.price, unit: "#{current_user.currency_code}", format: "%n %u") %></b></h3>
    <% end  %>

    <!-- p class="text_bckg"><b class="text_bckg">Category: </b><%= product.category %></p -->
    <!-- p class="text_bckg"><b class="text_bckg">Subcategory: </b><%= product.subcategory %></p -->

    <div class="tile-left-span text_bckg">
      <b class="text_bckg">Product ID: <%= product.id %></b>
      <br>
      <% if current_user.try(:admin?) %>
        <b><%= link_to 'Show', product %></b>
        <b><%= link_to 'Edit', edit_product_path(product) %></b>
        <b><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></b>
      <% end %>
    </div>

    <div class="tile-right-span text_bckg">
      <a href="/cart/more/<%= product.id %>" class="button">Add to Cart</a>
    </div>

  </div>
<% end %>

<h1 class="apart"><%= link_to "See your Cart", cart_path %></h1>

app/views/products/new.html.erb
<% if current_user.try(:admin?) %>

  <h1>New Product</h1>

  <%= render 'form' %>

  <%= link_to 'Back', products_path %>

<% else  %>

  <br><br>
  <h2>Sorry! You are not an Administrator! </h2>

<% end %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="tile">
  <div><%= image_tag @product.image_url, class: "image_size" %></div>
  <h3 class="text_bckg"><b>Title: </b><%= @product.title %></h3>
  <p class="text_bckg"><b>Description: </b><%= @product.description %></p>
  <% if current_user.try(:admin?) %>
    <p class="text_bckg"><b>Image URL: </b><%= @product.image_url %></p>
  <% end %>
  <p class="text_bckg"><b>Unit Price: </b><%= @product.price %> <%= current_user.currency_code %></p>
  <p class="text_bckg"><b>Category: </b><%= @product.category %></p>
  <p class="text_bckg"><b>Subcategory: </b><%= @product.subcategory %></p>
  <br>
  <p class="tile-left-span"><b>Product ID: </b><%= @product.id %></p>
</div>

<% if current_user.try(:admin?) %>
  <h4 class="apart"><%= link_to 'Edit', edit_product_path %></h4>
<% end %>

<h4 class="apart"><%= link_to 'Back', products_path %></h4>