config/routes.rb
Rails.application.routes.draw do

  resources :relays, :only => [:create, :show, :index]

  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/more/:id' => 'cart#add'
  get '/cart/less/:id' => 'cart#substract'

  resources :products
  root 'products#index'

  get 'about', to: "page#about"

  get 'faqs', to: "page#faqs"

  get 'contact', to: "page#contact"

  get 'now', to: "page#now"

  get 'css_file', to: "page#css_file"

  get 'pnb', to: "page#pnb"

  get 'page/iframe'

  resources :products

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cart2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav id="nav">
  <div id="page_nav">
    <%#= link_to "Home", root_path %>
    <%= link_to "Shop", products_path %>
    <%= link_to "Cart", cart_path %>
    <%= link_to "Transactions", relays_path %>
    <%#= link_to "About", page_about_path %>
    <%#= link_to "FAQs", page_faqs_path %>
    <%#= link_to "Contact us", page_contact_path %>
  </div>

  <div id="page_nav">
    <%if user_signed_in? %>
      <% if current_user.admin? %>
        <%= link_to "iFrame View", page_iframe_path %>
      <% end %>
    <% end %>
  </div>

  <div id="sign_in">
    <%if user_signed_in? %>
      Logged in as <strong><%= current_user.username %></strong>
      <%= link_to "Edit profile", edit_user_registration_path %>
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Log In", new_user_session_path %>
    <% end %>
  </div>
</nav>

<div id="main_wrap">
  <p class="notice"><%= notice %></p>
  <!-- p class="alert"><%= alert %></p -->
  <%= yield %>
</div>

</body>
</html>